server:
  port: 8080

spring:
  application:
    name: spring-secrity

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

